CREATE PROC FI_SP_IncBeneficiario
	@IDCLIENTE     BIGINT,
    @NOME          VARCHAR (50) ,
    @CPF VARCHAR(11)
AS
BEGIN
	INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE) 
	VALUES (@CPF, @NOME, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END