CREATE PROCEDURE FI_SP_VerificaBeneficiario
    @CPF VARCHAR(11),
    @IDCLIENTE BIGINT,
    @ID BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        COUNT(1) AS Existe
    FROM BENEFICIARIOS
    WHERE CPF = @CPF
    AND IDCLIENTE = @IDCLIENTE
    AND ID <> @ID
END