CREATE PROC FI_SP_AltBeneficiario
    @IDCLIENTE     BIGINT,
    @NOME          VARCHAR (50) ,
    @CPF VARCHAR(11),
	@Id           BIGINT
AS
BEGIN
	UPDATE BENEFICIARIOS 
	SET 
		NOME = @NOME, 
		CPF = @CPF,
		IDCLIENTE = @IDCLIENTE
	WHERE Id = @Id
END